#!/usr/bin/env python3
"""
seed_catalog.py — Task Zero for Context-to-Cart
=================================================
Seeds the existing ProductCatalog DynamoDB table with 80 realistic Indian SKUs.

Usage:
    python seed_catalog.py

Requirements:
    - AWS CLI configured with valid credentials
    - ProductCatalog table must already exist in DynamoDB (us-east-1)
    - On-demand billing mode, partition key: sku (String)

Idempotency:
    Uses put_item semantics (overwrites existing items with same sku).
    Safe to run multiple times — no duplicates created.
"""

import sys
import time
import boto3
from decimal import Decimal

# ---------------------------------------------------------------------------
# Configuration (inline to keep this script standalone / zero-dependency)
# ---------------------------------------------------------------------------
AWS_REGION = "us-east-1"
TABLE_NAME = "ProductCatalog"

# ---------------------------------------------------------------------------
# All 80 SKUs — Realistic Indian product catalog
# ---------------------------------------------------------------------------
PRODUCTS = [
    # =====================================================================
    # GRAINS (8 SKUs)
    # =====================================================================
    {
        "sku": "SKU-GRN-001",
        "name": "india gate classic basmati rice",
        "category": "grains",
        "subcategory": "rice",
        "brand": "India Gate",
        "price_inr": Decimal("189"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.5"),
        "in_stock": True,
        "keywords": {"rice", "basmati", "long grain", "pulao", "biryani", "india gate", "chawal"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"biryani", "pulao", "everyday", "rice dish"},
    },
    {
        "sku": "SKU-GRN-002",
        "name": "daawat rozana basmati rice",
        "category": "grains",
        "subcategory": "rice",
        "brand": "Daawat",
        "price_inr": Decimal("139"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"rice", "basmati", "rozana", "everyday", "daawat", "chawal", "pulao"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"biryani", "everyday", "budget"},
    },
    {
        "sku": "SKU-GRN-003",
        "name": "aashirvaad whole wheat atta",
        "category": "grains",
        "subcategory": "flour",
        "brand": "Aashirvaad",
        "price_inr": Decimal("269"),
        "unit": "g",
        "unit_quantity": Decimal("5000"),
        "rating": Decimal("4.6"),
        "in_stock": True,
        "keywords": {"atta", "wheat", "flour", "whole wheat", "roti", "chapati", "aashirvaad"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "roti", "chapati", "breakfast"},
    },
    {
        "sku": "SKU-GRN-004",
        "name": "aashirvaad multigrain atta",
        "category": "grains",
        "subcategory": "flour",
        "brand": "Aashirvaad",
        "price_inr": Decimal("75"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.4"),
        "in_stock": True,
        "keywords": {"atta", "multigrain", "flour", "healthy", "roti", "aashirvaad", "wheat"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"healthy", "everyday", "roti"},
    },
    {
        "sku": "SKU-GRN-005",
        "name": "mtr poha flattened rice",
        "category": "grains",
        "subcategory": "poha",
        "brand": "MTR",
        "price_inr": Decimal("45"),
        "unit": "g",
        "unit_quantity": Decimal("500"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"poha", "flattened rice", "chivda", "flakes", "mtr", "breakfast"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"breakfast", "snack", "quick meal"},
    },
    {
        "sku": "SKU-GRN-006",
        "name": "24 mantra organic sooji rava",
        "category": "grains",
        "subcategory": "semolina",
        "brand": "24 Mantra",
        "price_inr": Decimal("55"),
        "unit": "g",
        "unit_quantity": Decimal("500"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"sooji", "rava", "semolina", "suji", "upma", "halwa", "organic"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"breakfast", "dessert", "upma", "halwa"},
    },
    {
        "sku": "SKU-GRN-007",
        "name": "pillsbury maida all purpose flour",
        "category": "grains",
        "subcategory": "flour",
        "brand": "Pillsbury",
        "price_inr": Decimal("42"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.1"),
        "in_stock": True,
        "keywords": {"maida", "all purpose flour", "refined flour", "baking", "naan", "pillsbury"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"baking", "naan", "paratha"},
    },
    {
        "sku": "SKU-GRN-008",
        "name": "india gate broken basmati rice",
        "category": "grains",
        "subcategory": "rice",
        "brand": "India Gate",
        "price_inr": Decimal("89"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.0"),
        "in_stock": True,
        "keywords": {"rice", "broken rice", "tukda", "khichdi", "porridge", "india gate"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "khichdi", "budget"},
    },

    # =====================================================================
    # DAIRY (7 SKUs)
    # =====================================================================
    {
        "sku": "SKU-DRY-001",
        "name": "amul taaza toned milk",
        "category": "dairy",
        "subcategory": "milk",
        "brand": "Amul",
        "price_inr": Decimal("68"),
        "unit": "ml",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.4"),
        "in_stock": True,
        "keywords": {"milk", "toned milk", "amul", "taaza", "dudh", "dairy"}, "dietary": ["veg"],
        "tags": {"everyday", "breakfast", "tea", "coffee"},
    },
    {
        "sku": "SKU-DRY-002",
        "name": "amul butter",
        "category": "dairy",
        "subcategory": "butter",
        "brand": "Amul",
        "price_inr": Decimal("275"),
        "unit": "g",
        "unit_quantity": Decimal("500"),
        "rating": Decimal("4.7"),
        "in_stock": True,
        "keywords": {"butter", "amul", "makkhan", "spread", "dairy", "cooking"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "baking", "breakfast", "cooking"},
    },
    {
        "sku": "SKU-DRY-003",
        "name": "amul fresh paneer",
        "category": "dairy",
        "subcategory": "paneer",
        "brand": "Amul",
        "price_inr": Decimal("90"),
        "unit": "g",
        "unit_quantity": Decimal("200"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"paneer", "cottage cheese", "amul", "fresh", "tofu alternative", "protein"}, "dietary": ["veg"],
        "tags": {"curry", "tikka", "everyday", "protein"},
    },
    {
        "sku": "SKU-DRY-004",
        "name": "mother dairy classic curd",
        "category": "dairy",
        "subcategory": "curd",
        "brand": "Mother Dairy",
        "price_inr": Decimal("40"),
        "unit": "g",
        "unit_quantity": Decimal("400"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"curd", "dahi", "yogurt", "mother dairy", "raita", "probiotic"}, "dietary": ["veg"],
        "tags": {"everyday", "raita", "breakfast", "healthy"},
    },
    {
        "sku": "SKU-DRY-005",
        "name": "amul processed cheese slices",
        "category": "dairy",
        "subcategory": "cheese",
        "brand": "Amul",
        "price_inr": Decimal("105"),
        "unit": "g",
        "unit_quantity": Decimal("200"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"cheese", "processed cheese", "amul", "slices", "sandwich", "toast"}, "dietary": ["veg"],
        "tags": {"sandwich", "snack", "breakfast"},
    },
    {
        "sku": "SKU-DRY-006",
        "name": "amul pure ghee",
        "category": "dairy",
        "subcategory": "ghee",
        "brand": "Amul",
        "price_inr": Decimal("315"),
        "unit": "ml",
        "unit_quantity": Decimal("500"),
        "rating": Decimal("4.6"),
        "in_stock": True,
        "keywords": {"ghee", "clarified butter", "amul", "desi ghee", "pure ghee", "cooking"}, "dietary": ["veg"],
        "tags": {"cooking", "biryani", "dal", "everyday"},
    },
    {
        "sku": "SKU-DRY-007",
        "name": "nestle milkmaid condensed milk",
        "category": "dairy",
        "subcategory": "condensed milk",
        "brand": "Nestle",
        "price_inr": Decimal("159"),
        "unit": "g",
        "unit_quantity": Decimal("400"),
        "rating": Decimal("4.5"),
        "in_stock": True,
        "keywords": {"condensed milk", "milkmaid", "nestle", "sweet", "dessert", "baking"}, "dietary": ["veg"],
        "tags": {"dessert", "baking", "sweet"},
    },

    # =====================================================================
    # VEGETABLES (6 SKUs)
    # =====================================================================
    {
        "sku": "SKU-VEG-001",
        "name": "fresh onion",
        "category": "vegetables",
        "subcategory": "root vegetable",
        "brand": "Fresh",
        "price_inr": Decimal("35"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.0"),
        "in_stock": True,
        "keywords": {"onion", "pyaaz", "kanda", "vegetable", "fresh", "cooking"}, "dietary": ["veg", "vegan"],
        "tags": {"everyday", "cooking", "base vegetable"},
    },
    {
        "sku": "SKU-VEG-002",
        "name": "fresh potato",
        "category": "vegetables",
        "subcategory": "root vegetable",
        "brand": "Fresh",
        "price_inr": Decimal("30"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.0"),
        "in_stock": True,
        "keywords": {"potato", "aloo", "vegetable", "fresh", "cooking", "starch"}, "dietary": ["veg", "vegan"],
        "tags": {"everyday", "cooking", "curry", "fry"},
    },
    {
        "sku": "SKU-VEG-003",
        "name": "fresh tomato",
        "category": "vegetables",
        "subcategory": "fruit vegetable",
        "brand": "Fresh",
        "price_inr": Decimal("25"),
        "unit": "g",
        "unit_quantity": Decimal("500"),
        "rating": Decimal("3.9"),
        "in_stock": True,
        "keywords": {"tomato", "tamatar", "vegetable", "fresh", "cooking", "gravy"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "cooking", "base vegetable", "gravy"},
    },
    {
        "sku": "SKU-VEG-004",
        "name": "fresh garlic",
        "category": "vegetables",
        "subcategory": "seasoning",
        "brand": "Fresh",
        "price_inr": Decimal("45"),
        "unit": "g",
        "unit_quantity": Decimal("250"),
        "rating": Decimal("4.1"),
        "in_stock": True,
        "keywords": {"garlic", "lehsun", "lahsun", "seasoning", "fresh", "clove"}, "dietary": ["veg", "vegan"],
        "tags": {"cooking", "seasoning", "everyday"},
    },
    {
        "sku": "SKU-VEG-005",
        "name": "fresh ginger",
        "category": "vegetables",
        "subcategory": "seasoning",
        "brand": "Fresh",
        "price_inr": Decimal("15"),
        "unit": "g",
        "unit_quantity": Decimal("100"),
        "rating": Decimal("4.0"),
        "in_stock": True,
        "keywords": {"ginger", "adrak", "seasoning", "fresh", "root", "cooking"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"cooking", "tea", "seasoning", "everyday"},
    },
    {
        "sku": "SKU-VEG-006",
        "name": "fresh green chili",
        "category": "vegetables",
        "subcategory": "chili",
        "brand": "Fresh",
        "price_inr": Decimal("10"),
        "unit": "g",
        "unit_quantity": Decimal("100"),
        "rating": Decimal("3.8"),
        "in_stock": True,
        "keywords": {"green chili", "hari mirch", "chili", "chilli", "spicy", "fresh"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"cooking", "spicy", "everyday", "garnish"},
    },

    # =====================================================================
    # FRUITS (5 SKUs)
    # =====================================================================
    {
        "sku": "SKU-FRT-001",
        "name": "fresh banana",
        "category": "fruits",
        "subcategory": "tropical fruit",
        "brand": "Fresho",
        "price_inr": Decimal("50"),
        "unit": "piece",
        "unit_quantity": Decimal("12"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"banana", "kela", "fruit", "fresh", "dozen", "yellow"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"breakfast", "healthy", "snack", "smoothie"},
    },
    {
        "sku": "SKU-FRT-002",
        "name": "fresh apple shimla",
        "category": "fruits",
        "subcategory": "temperate fruit",
        "brand": "Fresho",
        "price_inr": Decimal("180"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"apple", "seb", "fruit", "fresh", "shimla", "red apple"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"healthy", "snack", "breakfast"},
    },
    {
        "sku": "SKU-FRT-003",
        "name": "fresh lemon",
        "category": "fruits",
        "subcategory": "citrus",
        "brand": "Fresho",
        "price_inr": Decimal("25"),
        "unit": "g",
        "unit_quantity": Decimal("250"),
        "rating": Decimal("4.0"),
        "in_stock": True,
        "keywords": {"lemon", "nimbu", "lime", "citrus", "fresh", "juice"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"cooking", "garnish", "drink", "everyday"},
    },
    {
        "sku": "SKU-FRT-004",
        "name": "fresh mango alphonso",
        "category": "fruits",
        "subcategory": "tropical fruit",
        "brand": "Fresho",
        "price_inr": Decimal("120"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.7"),
        "in_stock": True,
        "keywords": {"mango", "aam", "alphonso", "fruit", "fresh", "hapus"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"seasonal", "dessert", "smoothie", "summer"},
    },
    {
        "sku": "SKU-FRT-005",
        "name": "fresh orange nagpur",
        "category": "fruits",
        "subcategory": "citrus",
        "brand": "Fresho",
        "price_inr": Decimal("80"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.1"),
        "in_stock": True,
        "keywords": {"orange", "santra", "citrus", "fruit", "fresh", "nagpur", "juice"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"healthy", "juice", "snack", "breakfast"},
    },

    # =====================================================================
    # SPICES (10 SKUs)
    # =====================================================================
    {
        "sku": "SKU-SPC-001",
        "name": "mdh turmeric powder haldi",
        "category": "spices",
        "subcategory": "ground spice",
        "brand": "MDH",
        "price_inr": Decimal("42"),
        "unit": "g",
        "unit_quantity": Decimal("100"),
        "rating": Decimal("4.4"),
        "in_stock": True,
        "keywords": {"turmeric", "haldi", "powder", "mdh", "spice", "yellow"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "cooking", "curry", "dal"},
    },
    {
        "sku": "SKU-SPC-002",
        "name": "mdh red chili powder",
        "category": "spices",
        "subcategory": "ground spice",
        "brand": "MDH",
        "price_inr": Decimal("55"),
        "unit": "g",
        "unit_quantity": Decimal("100"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"red chili", "lal mirch", "chili powder", "mdh", "spice", "hot"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "cooking", "spicy", "curry"},
    },
    {
        "sku": "SKU-SPC-003",
        "name": "mdh coriander powder dhaniya",
        "category": "spices",
        "subcategory": "ground spice",
        "brand": "MDH",
        "price_inr": Decimal("38"),
        "unit": "g",
        "unit_quantity": Decimal("100"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"coriander", "dhaniya", "powder", "mdh", "spice", "ground"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "cooking", "curry", "dal"},
    },
    {
        "sku": "SKU-SPC-004",
        "name": "everest cumin powder jeera",
        "category": "spices",
        "subcategory": "ground spice",
        "brand": "Everest",
        "price_inr": Decimal("75"),
        "unit": "g",
        "unit_quantity": Decimal("100"),
        "rating": Decimal("4.4"),
        "in_stock": True,
        "keywords": {"cumin", "jeera", "powder", "everest", "spice", "ground cumin"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "cooking", "curry", "raita"},
    },
    {
        "sku": "SKU-SPC-005",
        "name": "mdh garam masala",
        "category": "spices",
        "subcategory": "blended spice",
        "brand": "MDH",
        "price_inr": Decimal("85"),
        "unit": "g",
        "unit_quantity": Decimal("100"),
        "rating": Decimal("4.5"),
        "in_stock": True,
        "keywords": {"garam masala", "masala", "mdh", "spice blend", "mixed spice", "all spice"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"curry", "biryani", "everyday", "gravy"},
    },
    {
        "sku": "SKU-SPC-006",
        "name": "everest biryani masala",
        "category": "spices",
        "subcategory": "blended spice",
        "brand": "Everest",
        "price_inr": Decimal("55"),
        "unit": "g",
        "unit_quantity": Decimal("50"),
        "rating": Decimal("4.6"),
        "in_stock": True,
        "keywords": {"biryani masala", "biryani", "masala", "everest", "spice", "rice masala"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"biryani", "pulao", "rice dish"},
    },
    {
        "sku": "SKU-SPC-007",
        "name": "catch black pepper powder kali mirch",
        "category": "spices",
        "subcategory": "ground spice",
        "brand": "Catch",
        "price_inr": Decimal("65"),
        "unit": "g",
        "unit_quantity": Decimal("50"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"black pepper", "kali mirch", "pepper", "catch", "spice", "ground pepper"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "seasoning", "soup", "salad"},
    },
    {
        "sku": "SKU-SPC-008",
        "name": "catch cumin seeds jeera whole",
        "category": "spices",
        "subcategory": "whole spice",
        "brand": "Catch",
        "price_inr": Decimal("78"),
        "unit": "g",
        "unit_quantity": Decimal("100"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"cumin seeds", "jeera", "whole cumin", "catch", "spice", "tadka", "tempering"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "tadka", "dal", "cooking"},
    },
    {
        "sku": "SKU-SPC-009",
        "name": "mdh chana masala",
        "category": "spices",
        "subcategory": "blended spice",
        "brand": "MDH",
        "price_inr": Decimal("52"),
        "unit": "g",
        "unit_quantity": Decimal("100"),
        "rating": Decimal("4.4"),
        "in_stock": True,
        "keywords": {"chana masala", "chole masala", "chickpea", "mdh", "masala", "spice"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"curry", "chole", "chickpea", "north indian"},
    },
    {
        "sku": "SKU-SPC-010",
        "name": "tata salt iodized",
        "category": "spices",
        "subcategory": "salt",
        "brand": "Tata",
        "price_inr": Decimal("28"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.6"),
        "in_stock": True,
        "keywords": {"salt", "namak", "tata", "iodized", "table salt", "cooking salt"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "cooking", "essential"},
    },

    # =====================================================================
    # OILS (5 SKUs)
    # =====================================================================
    {
        "sku": "SKU-OIL-001",
        "name": "fortune sunflower refined oil",
        "category": "oils",
        "subcategory": "cooking oil",
        "brand": "Fortune",
        "price_inr": Decimal("155"),
        "unit": "ml",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"sunflower oil", "refined oil", "cooking oil", "fortune", "vegetable oil", "frying"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "cooking", "frying"},
    },
    {
        "sku": "SKU-OIL-002",
        "name": "saffola gold blended oil",
        "category": "oils",
        "subcategory": "cooking oil",
        "brand": "Saffola",
        "price_inr": Decimal("189"),
        "unit": "ml",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.4"),
        "in_stock": True,
        "keywords": {"saffola", "blended oil", "cooking oil", "heart healthy", "gold", "vegetable oil"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "cooking", "healthy"},
    },
    {
        "sku": "SKU-OIL-003",
        "name": "figaro olive oil",
        "category": "oils",
        "subcategory": "specialty oil",
        "brand": "Figaro",
        "price_inr": Decimal("275"),
        "unit": "ml",
        "unit_quantity": Decimal("250"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"olive oil", "figaro", "extra virgin", "salad oil", "healthy oil", "cooking"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"salad", "healthy", "italian", "baking"},
    },
    {
        "sku": "SKU-OIL-004",
        "name": "klf coconut oil",
        "category": "oils",
        "subcategory": "cooking oil",
        "brand": "KLF",
        "price_inr": Decimal("130"),
        "unit": "ml",
        "unit_quantity": Decimal("500"),
        "rating": Decimal("4.5"),
        "in_stock": True,
        "keywords": {"coconut oil", "nariyal tel", "klf", "cooking oil", "coconut", "south indian"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"south indian", "cooking", "hair", "everyday"},
    },
    {
        "sku": "SKU-OIL-005",
        "name": "dhara mustard oil kachi ghani",
        "category": "oils",
        "subcategory": "cooking oil",
        "brand": "Dhara",
        "price_inr": Decimal("165"),
        "unit": "ml",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"mustard oil", "sarson tel", "kachi ghani", "dhara", "cooking oil", "pickle"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "cooking", "pickle", "north indian"},
    },

    # =====================================================================
    # BEVERAGES (8 SKUs)
    # =====================================================================
    {
        "sku": "SKU-BEV-001",
        "name": "coca-cola soft drink",
        "category": "beverages",
        "subcategory": "carbonated",
        "brand": "Coca-Cola",
        "price_inr": Decimal("38"),
        "unit": "ml",
        "unit_quantity": Decimal("750"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"coca cola", "coke", "cold drink", "soft drink", "soda", "carbonated", "cola"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"party", "snack", "cold drink"},
    },
    {
        "sku": "SKU-BEV-002",
        "name": "sprite lemon lime drink",
        "category": "beverages",
        "subcategory": "carbonated",
        "brand": "Sprite",
        "price_inr": Decimal("38"),
        "unit": "ml",
        "unit_quantity": Decimal("750"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"sprite", "lemon", "lime", "cold drink", "soft drink", "soda", "carbonated"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"party", "cold drink", "refreshing"},
    },
    {
        "sku": "SKU-BEV-003",
        "name": "paperboat aamras mango drink",
        "category": "beverages",
        "subcategory": "juice",
        "brand": "Paperboat",
        "price_inr": Decimal("30"),
        "unit": "ml",
        "unit_quantity": Decimal("200"),
        "rating": Decimal("4.5"),
        "in_stock": True,
        "keywords": {"paperboat", "aamras", "mango", "juice", "drink", "fruit drink"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"party", "snack", "summer", "juice"},
    },
    {
        "sku": "SKU-BEV-004",
        "name": "real fruit power mango juice",
        "category": "beverages",
        "subcategory": "juice",
        "brand": "Real",
        "price_inr": Decimal("99"),
        "unit": "ml",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"real", "mango juice", "fruit juice", "juice", "drink", "mango"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"party", "breakfast", "juice", "healthy"},
    },
    {
        "sku": "SKU-BEV-005",
        "name": "bisleri mineral water",
        "category": "beverages",
        "subcategory": "water",
        "brand": "Bisleri",
        "price_inr": Decimal("20"),
        "unit": "ml",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.0"),
        "in_stock": True,
        "keywords": {"water", "mineral water", "bisleri", "drinking water", "packaged water", "paani"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "essential"},
    },
    {
        "sku": "SKU-BEV-006",
        "name": "tata tea gold",
        "category": "beverages",
        "subcategory": "tea",
        "brand": "Tata",
        "price_inr": Decimal("255"),
        "unit": "g",
        "unit_quantity": Decimal("500"),
        "rating": Decimal("4.5"),
        "in_stock": True,
        "keywords": {"tea", "chai", "tata tea", "gold", "black tea", "leaf tea"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "breakfast", "chai"},
    },
    {
        "sku": "SKU-BEV-007",
        "name": "nescafe classic instant coffee",
        "category": "beverages",
        "subcategory": "coffee",
        "brand": "Nescafe",
        "price_inr": Decimal("245"),
        "unit": "g",
        "unit_quantity": Decimal("100"),
        "rating": Decimal("4.4"),
        "in_stock": True,
        "keywords": {"coffee", "nescafe", "instant coffee", "classic", "caffeine", "hot drink"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "breakfast", "office"},
    },
    {
        "sku": "SKU-BEV-008",
        "name": "tropicana orange juice",
        "category": "beverages",
        "subcategory": "juice",
        "brand": "Tropicana",
        "price_inr": Decimal("110"),
        "unit": "ml",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"orange juice", "tropicana", "juice", "fruit juice", "citrus", "drink"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"breakfast", "healthy", "juice"},
    },

    # =====================================================================
    # SNACKS (8 SKUs)
    # =====================================================================
    {
        "sku": "SKU-SNK-001",
        "name": "haldirams aloo bhujia namkeen",
        "category": "snacks",
        "subcategory": "namkeen",
        "brand": "Haldirams",
        "price_inr": Decimal("65"),
        "unit": "g",
        "unit_quantity": Decimal("200"),
        "rating": Decimal("4.4"),
        "in_stock": True,
        "keywords": {"bhujia", "aloo bhujia", "namkeen", "haldirams", "snack", "crispy", "sev"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"party", "snack", "tea time", "namkeen"},
    },
    {
        "sku": "SKU-SNK-002",
        "name": "lays classic salted chips",
        "category": "snacks",
        "subcategory": "chips",
        "brand": "Lays",
        "price_inr": Decimal("20"),
        "unit": "g",
        "unit_quantity": Decimal("52"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"chips", "lays", "potato chips", "salted", "crispy", "snack", "wafers"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"party", "snack", "movie night"},
    },
    {
        "sku": "SKU-SNK-003",
        "name": "parle-g glucose biscuits",
        "category": "snacks",
        "subcategory": "biscuits",
        "brand": "Parle",
        "price_inr": Decimal("55"),
        "unit": "g",
        "unit_quantity": Decimal("800"),
        "rating": Decimal("4.6"),
        "in_stock": True,
        "keywords": {"biscuit", "parle-g", "glucose", "parle", "cookies", "chai snack", "tea biscuit"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"everyday", "tea time", "breakfast", "snack"},
    },
    {
        "sku": "SKU-SNK-004",
        "name": "kurkure masala munch",
        "category": "snacks",
        "subcategory": "puffed snack",
        "brand": "Kurkure",
        "price_inr": Decimal("20"),
        "unit": "g",
        "unit_quantity": Decimal("90"),
        "rating": Decimal("4.1"),
        "in_stock": True,
        "keywords": {"kurkure", "masala", "snack", "crunchy", "munch", "puffed", "crispy"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"party", "snack", "tea time"},
    },
    {
        "sku": "SKU-SNK-005",
        "name": "britannia good day butter cookies",
        "category": "snacks",
        "subcategory": "biscuits",
        "brand": "Britannia",
        "price_inr": Decimal("140"),
        "unit": "g",
        "unit_quantity": Decimal("600"),
        "rating": Decimal("4.4"),
        "in_stock": True,
        "keywords": {"biscuit", "cookies", "britannia", "good day", "butter", "snack"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"tea time", "snack", "everyday"},
    },
    {
        "sku": "SKU-SNK-006",
        "name": "act ii instant popcorn butter",
        "category": "snacks",
        "subcategory": "popcorn",
        "brand": "Act II",
        "price_inr": Decimal("40"),
        "unit": "g",
        "unit_quantity": Decimal("70"),
        "rating": Decimal("4.0"),
        "in_stock": True,
        "keywords": {"popcorn", "act ii", "microwave", "butter", "instant", "snack", "movie"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"party", "movie night", "snack", "quick"},
    },
    {
        "sku": "SKU-SNK-007",
        "name": "haldirams namkeen mixture",
        "category": "snacks",
        "subcategory": "namkeen",
        "brand": "Haldirams",
        "price_inr": Decimal("115"),
        "unit": "g",
        "unit_quantity": Decimal("400"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"namkeen", "mixture", "haldirams", "snack", "farsan", "mixed", "savory"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"party", "snack", "tea time", "diwali"},
    },
    {
        "sku": "SKU-SNK-008",
        "name": "britannia bourbon chocolate cream biscuit",
        "category": "snacks",
        "subcategory": "biscuits",
        "brand": "Britannia",
        "price_inr": Decimal("70"),
        "unit": "g",
        "unit_quantity": Decimal("300"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"bourbon", "chocolate", "biscuit", "cream", "britannia", "cookies", "snack"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"snack", "tea time", "chocolate"},
    },

    # =====================================================================
    # CLEANING (6 SKUs)
    # =====================================================================
    {
        "sku": "SKU-CLN-001",
        "name": "ariel matic washing detergent powder",
        "category": "cleaning",
        "subcategory": "detergent",
        "brand": "Ariel",
        "price_inr": Decimal("299"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.5"),
        "in_stock": True,
        "keywords": {"detergent", "washing powder", "ariel", "matic", "laundry", "clothes wash"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"cleaning", "laundry", "everyday"},
    },
    {
        "sku": "SKU-CLN-002",
        "name": "surf excel easy wash detergent",
        "category": "cleaning",
        "subcategory": "detergent",
        "brand": "Surf Excel",
        "price_inr": Decimal("199"),
        "unit": "g",
        "unit_quantity": Decimal("1000"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"detergent", "surf excel", "washing powder", "laundry", "clothes wash", "easy wash"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"cleaning", "laundry", "everyday"},
    },
    {
        "sku": "SKU-CLN-003",
        "name": "vim dishwash gel lemon",
        "category": "cleaning",
        "subcategory": "dishwash",
        "brand": "Vim",
        "price_inr": Decimal("99"),
        "unit": "ml",
        "unit_quantity": Decimal("500"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"dishwash", "vim", "dish soap", "gel", "utensil cleaner", "kitchen"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"cleaning", "kitchen", "everyday"},
    },
    {
        "sku": "SKU-CLN-004",
        "name": "lizol floor cleaner citrus",
        "category": "cleaning",
        "subcategory": "floor cleaner",
        "brand": "Lizol",
        "price_inr": Decimal("115"),
        "unit": "ml",
        "unit_quantity": Decimal("500"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"floor cleaner", "lizol", "disinfectant", "mopping", "surface cleaner", "citrus"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"cleaning", "floor", "disinfect"},
    },
    {
        "sku": "SKU-CLN-005",
        "name": "harpic toilet cleaner original",
        "category": "cleaning",
        "subcategory": "toilet cleaner",
        "brand": "Harpic",
        "price_inr": Decimal("89"),
        "unit": "ml",
        "unit_quantity": Decimal("500"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"toilet cleaner", "harpic", "bathroom", "disinfectant", "commode", "cleaning"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"cleaning", "bathroom", "disinfect"},
    },
    {
        "sku": "SKU-CLN-006",
        "name": "dettol original handwash",
        "category": "cleaning",
        "subcategory": "handwash",
        "brand": "Dettol",
        "price_inr": Decimal("65"),
        "unit": "ml",
        "unit_quantity": Decimal("200"),
        "rating": Decimal("4.4"),
        "in_stock": True,
        "keywords": {"handwash", "dettol", "hand soap", "antibacterial", "hygiene", "liquid soap"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"cleaning", "hygiene", "everyday"},
    },

    # =====================================================================
    # STATIONERY (7 SKUs)
    # =====================================================================
    {
        "sku": "SKU-STN-001",
        "name": "classmate long notebook 180 pages ruled",
        "category": "stationery",
        "subcategory": "notebook",
        "brand": "Classmate",
        "price_inr": Decimal("65"),
        "unit": "piece",
        "unit_quantity": Decimal("1"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"notebook", "classmate", "ruled", "register", "copy", "writing", "long book"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"school", "office", "writing"},
    },
    {
        "sku": "SKU-STN-002",
        "name": "natraj hb pencil pack of 10",
        "category": "stationery",
        "subcategory": "pencils",
        "brand": "Natraj",
        "price_inr": Decimal("45"),
        "unit": "pack",
        "unit_quantity": Decimal("10"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"pencil", "natraj", "hb", "writing", "school", "drawing", "lead pencil"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"school", "drawing", "writing"},
    },
    {
        "sku": "SKU-STN-003",
        "name": "cello butterflow blue ball pen pack of 5",
        "category": "stationery",
        "subcategory": "pens",
        "brand": "Cello",
        "price_inr": Decimal("75"),
        "unit": "pack",
        "unit_quantity": Decimal("5"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"pen", "ball pen", "cello", "butterflow", "blue pen", "writing"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"school", "office", "writing", "exam"},
    },
    {
        "sku": "SKU-STN-004",
        "name": "apsara non-dust eraser pack of 5",
        "category": "stationery",
        "subcategory": "erasers",
        "brand": "Apsara",
        "price_inr": Decimal("30"),
        "unit": "pack",
        "unit_quantity": Decimal("5"),
        "rating": Decimal("4.1"),
        "in_stock": True,
        "keywords": {"eraser", "rubber", "apsara", "non-dust", "school", "clean erase"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"school", "drawing", "writing"},
    },
    {
        "sku": "SKU-STN-005",
        "name": "faber-castell sharpener pack of 5",
        "category": "stationery",
        "subcategory": "sharpeners",
        "brand": "Faber-Castell",
        "price_inr": Decimal("25"),
        "unit": "pack",
        "unit_quantity": Decimal("5"),
        "rating": Decimal("4.0"),
        "in_stock": True,
        "keywords": {"sharpener", "pencil sharpener", "faber-castell", "school", "metal"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"school", "drawing"},
    },
    {
        "sku": "SKU-STN-006",
        "name": "camlin geometry box set",
        "category": "stationery",
        "subcategory": "instruments",
        "brand": "Camlin",
        "price_inr": Decimal("125"),
        "unit": "piece",
        "unit_quantity": Decimal("1"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"geometry box", "compass", "protractor", "ruler", "camlin", "maths", "divider"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"school", "maths", "exam"},
    },
    {
        "sku": "SKU-STN-007",
        "name": "classmate colour pencils 12 shades",
        "category": "stationery",
        "subcategory": "art supplies",
        "brand": "Classmate",
        "price_inr": Decimal("85"),
        "unit": "pack",
        "unit_quantity": Decimal("12"),
        "rating": Decimal("4.1"),
        "in_stock": True,
        "keywords": {"colour pencils", "coloring", "classmate", "art", "drawing", "crayons", "color"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"school", "art", "drawing", "creative"},
    },

    # =====================================================================
    # TOOLS & HARDWARE (5 SKUs)
    # =====================================================================
    {
        "sku": "SKU-THW-001",
        "name": "stanley screwdriver set 6 piece",
        "category": "tools_hardware",
        "subcategory": "hand tools",
        "brand": "Stanley",
        "price_inr": Decimal("450"),
        "unit": "piece",
        "unit_quantity": Decimal("1"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"screwdriver", "stanley", "tool set", "phillips", "flathead", "repair"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"diy", "repair", "tools"},
    },
    {
        "sku": "SKU-THW-002",
        "name": "bosch measuring tape 5 metre",
        "category": "tools_hardware",
        "subcategory": "measuring",
        "brand": "Bosch",
        "price_inr": Decimal("250"),
        "unit": "piece",
        "unit_quantity": Decimal("1"),
        "rating": Decimal("4.4"),
        "in_stock": True,
        "keywords": {"measuring tape", "tape measure", "bosch", "ruler", "5m", "measurement"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"diy", "measurement", "tools"},
    },
    {
        "sku": "SKU-THW-003",
        "name": "generic ptfe plumber tape roll",
        "category": "tools_hardware",
        "subcategory": "plumbing",
        "brand": "Generic",
        "price_inr": Decimal("35"),
        "unit": "piece",
        "unit_quantity": Decimal("1"),
        "rating": Decimal("3.8"),
        "in_stock": True,
        "keywords": {"ptfe tape", "plumber tape", "teflon tape", "pipe tape", "sealing", "plumbing", "leak"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"diy", "plumbing", "repair", "leak fix"},
    },
    {
        "sku": "SKU-THW-004",
        "name": "generic adjustable wrench 8 inch",
        "category": "tools_hardware",
        "subcategory": "hand tools",
        "brand": "Generic",
        "price_inr": Decimal("320"),
        "unit": "piece",
        "unit_quantity": Decimal("1"),
        "rating": Decimal("4.0"),
        "in_stock": True,
        "keywords": {"wrench", "adjustable wrench", "spanner", "plumbing", "nut", "bolt", "repair"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"diy", "plumbing", "repair", "tools"},
    },
    {
        "sku": "SKU-THW-005",
        "name": "fevikwik instant adhesive",
        "category": "tools_hardware",
        "subcategory": "adhesive",
        "brand": "Fevikwik",
        "price_inr": Decimal("15"),
        "unit": "g",
        "unit_quantity": Decimal("3"),
        "rating": Decimal("4.1"),
        "in_stock": True,
        "keywords": {"glue", "adhesive", "fevikwik", "super glue", "instant", "bond", "fix"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"diy", "repair", "craft"},
    },

    # =====================================================================
    # MEDICINES OTC (5 SKUs)
    # =====================================================================
    {
        "sku": "SKU-MED-001",
        "name": "crocin pain relief paracetamol tablets",
        "category": "medicines_otc",
        "subcategory": "pain relief",
        "brand": "Crocin",
        "price_inr": Decimal("28"),
        "unit": "pack",
        "unit_quantity": Decimal("15"),
        "rating": Decimal("4.5"),
        "in_stock": True,
        "keywords": {"crocin", "paracetamol", "pain relief", "fever", "headache", "tablet", "medicine"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"medicine", "fever", "pain", "headache"},
    },
    {
        "sku": "SKU-MED-002",
        "name": "vicks vaporub balm",
        "category": "medicines_otc",
        "subcategory": "cold relief",
        "brand": "Vicks",
        "price_inr": Decimal("145"),
        "unit": "ml",
        "unit_quantity": Decimal("50"),
        "rating": Decimal("4.6"),
        "in_stock": True,
        "keywords": {"vicks", "vaporub", "cold", "cough", "balm", "congestion", "rub"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"medicine", "cold", "winter", "cough"},
    },
    {
        "sku": "SKU-MED-003",
        "name": "electral ors oral rehydration sachets",
        "category": "medicines_otc",
        "subcategory": "rehydration",
        "brand": "Electral",
        "price_inr": Decimal("52"),
        "unit": "pack",
        "unit_quantity": Decimal("4"),
        "rating": Decimal("4.3"),
        "in_stock": True,
        "keywords": {"ors", "electral", "rehydration", "dehydration", "electrolyte", "sachet", "oral"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"medicine", "summer", "rehydration"},
    },
    {
        "sku": "SKU-MED-004",
        "name": "volini pain relief spray",
        "category": "medicines_otc",
        "subcategory": "pain relief",
        "brand": "Volini",
        "price_inr": Decimal("155"),
        "unit": "g",
        "unit_quantity": Decimal("40"),
        "rating": Decimal("4.2"),
        "in_stock": True,
        "keywords": {"volini", "pain relief", "spray", "muscle pain", "joint pain", "sprain", "backache"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"medicine", "pain", "sports", "muscle"},
    },
    {
        "sku": "SKU-MED-005",
        "name": "dettol antiseptic liquid",
        "category": "medicines_otc",
        "subcategory": "antiseptic",
        "brand": "Dettol",
        "price_inr": Decimal("95"),
        "unit": "ml",
        "unit_quantity": Decimal("250"),
        "rating": Decimal("4.5"),
        "in_stock": True,
        "keywords": {"dettol", "antiseptic", "disinfectant", "wound", "first aid", "hygiene", "liquid"}, "dietary": ["veg", "vegan", "jain"],
        "tags": {"medicine", "first aid", "hygiene", "cleaning"},
    },
]


def seed_products():
    """
    Seed the ProductCatalog table using batch_writer (high-level wrapper
    over batch_write_item). Handles 25-item chunking automatically.

    Idempotent: put_item overwrites any existing item with the same sku.
    """
    dynamodb = boto3.resource("dynamodb", region_name=AWS_REGION)
    table = dynamodb.Table(TABLE_NAME)

    # Verify table is accessible
    try:
        status = table.table_status
        print(f"[OK] Table '{TABLE_NAME}' found -- status: {status}")
    except Exception as e:
        print(f"[FAIL] Cannot access table '{TABLE_NAME}': {e}")
        print("  Make sure the table exists in DynamoDB and AWS credentials are configured.")
        sys.exit(1)

    # Seed products
    print(f"\nSeeding {len(PRODUCTS)} products...")
    written = 0
    failed = 0

    with table.batch_writer() as batch:
        for product in PRODUCTS:
            try:
                batch.put_item(Item=product)
                written += 1
            except Exception as e:
                print(f"  [FAIL] Failed to write {product['sku']}: {e}")
                failed += 1

    print(f"\n{'='*50}")
    print(f"  Total products:  {len(PRODUCTS)}")
    print(f"  Written:         {written}")
    print(f"  Failed:          {failed}")
    print(f"{'='*50}")

    # Verify by scanning a few items
    print("\nVerification -- sampling first 5 items...")
    response = table.scan(Limit=5)
    for item in response.get("Items", []):
        print(f"  [OK] {item['sku']}: {item['name']} ({item['brand']}) -- Rs.{item['price_inr']}")

    # Count total items in table
    response = table.scan(Select="COUNT")
    total = response["Count"]
    print(f"\nTotal items in table: {total}")

    if total >= len(PRODUCTS):
        print("[OK] Seed complete -- all products written successfully!")
    else:
        print(f"[WARN] Expected {len(PRODUCTS)} items but found {total}. Re-run the script.")


def print_category_summary():
    """Print a summary of SKUs by category."""
    from collections import Counter
    cats = Counter(p["category"] for p in PRODUCTS)
    print("\nCategory distribution:")
    for cat, count in sorted(cats.items()):
        print(f"  {cat:20s} -- {count} SKUs")
    print(f"  {'TOTAL':20s} -- {sum(cats.values())} SKUs")


if __name__ == "__main__":
    print("=" * 50)
    print("  Context-to-Cart — Product Catalog Seeder")
    print("=" * 50)
    print(f"  Region: {AWS_REGION}")
    print(f"  Table:  {TABLE_NAME}")
    print(f"  SKUs:   {len(PRODUCTS)}")
    print()

    print_category_summary()
    print()

    seed_products()
