/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecipeRouteImport } from './routes/recipe'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as OccasionsRouteImport } from './routes/occasions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollabIdRouteImport } from './routes/collab.$id'
import { Route as CartIdRouteImport } from './routes/cart.$id'
import { Route as CollabJoinCodeRouteImport } from './routes/collab.join.$code'

const RecipeRoute = RecipeRouteImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsRoute = OccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabIdRoute = CollabIdRouteImport.update({
  id: '/collab/$id',
  path: '/collab/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIdRoute = CartIdRouteImport.update({
  id: '/cart/$id',
  path: '/cart/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabJoinCodeRoute = CollabJoinCodeRouteImport.update({
  id: '/collab/join/$code',
  path: '/collab/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/occasions': typeof OccasionsRoute
  '/preferences': typeof PreferencesRoute
  '/recipe': typeof RecipeRoute
  '/cart/$id': typeof CartIdRoute
  '/collab/$id': typeof CollabIdRoute
  '/collab/join/$code': typeof CollabJoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/occasions': typeof OccasionsRoute
  '/preferences': typeof PreferencesRoute
  '/recipe': typeof RecipeRoute
  '/cart/$id': typeof CartIdRoute
  '/collab/$id': typeof CollabIdRoute
  '/collab/join/$code': typeof CollabJoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/occasions': typeof OccasionsRoute
  '/preferences': typeof PreferencesRoute
  '/recipe': typeof RecipeRoute
  '/cart/$id': typeof CartIdRoute
  '/collab/$id': typeof CollabIdRoute
  '/collab/join/$code': typeof CollabJoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/login'
    | '/occasions'
    | '/preferences'
    | '/recipe'
    | '/cart/$id'
    | '/collab/$id'
    | '/collab/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/occasions'
    | '/preferences'
    | '/recipe'
    | '/cart/$id'
    | '/collab/$id'
    | '/collab/join/$code'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/login'
    | '/occasions'
    | '/preferences'
    | '/recipe'
    | '/cart/$id'
    | '/collab/$id'
    | '/collab/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  OccasionsRoute: typeof OccasionsRoute
  PreferencesRoute: typeof PreferencesRoute
  RecipeRoute: typeof RecipeRoute
  CartIdRoute: typeof CartIdRoute
  CollabIdRoute: typeof CollabIdRoute
  CollabJoinCodeRoute: typeof CollabJoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recipe': {
      id: '/recipe'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof RecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions': {
      id: '/occasions'
      path: '/occasions'
      fullPath: '/occasions'
      preLoaderRoute: typeof OccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/$id': {
      id: '/collab/$id'
      path: '/collab/$id'
      fullPath: '/collab/$id'
      preLoaderRoute: typeof CollabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/$id': {
      id: '/cart/$id'
      path: '/cart/$id'
      fullPath: '/cart/$id'
      preLoaderRoute: typeof CartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/join/$code': {
      id: '/collab/join/$code'
      path: '/collab/join/$code'
      fullPath: '/collab/join/$code'
      preLoaderRoute: typeof CollabJoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  OccasionsRoute: OccasionsRoute,
  PreferencesRoute: PreferencesRoute,
  RecipeRoute: RecipeRoute,
  CartIdRoute: CartIdRoute,
  CollabIdRoute: CollabIdRoute,
  CollabJoinCodeRoute: CollabJoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
