import type { WatchedItem } from "@/lib/watchlist-api";

function makeHistory(start: number, end: number, days = 30, dip?: number): { day: number; price: number }[] {
  const out: { day: number; price: number }[] = [];
  for (let i = 0; i < days; i++) {
    const t = i / (days - 1);
    const base = start + (end - start) * t;
    const noise = Math.sin(i * 1.3) * (start * 0.015) + Math.cos(i * 0.7) * (start * 0.01);
    let price = Math.round(base + noise);
    if (dip && i === days - 4) price = Math.round(dip);
    out.push({ day: i + 1, price });
  }
  return out;
}

export const MOCK_WATCHES: WatchedItem[] = [
  {
    watch_id: "mock-1",
    sku: "SONY-WH1000XM5",
    name: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    current_price_inr: 24990,
    target_price_inr: 23000,
    competitor_price_inr: 26499,
    competitor_source: "Flipkart",
    status: "price_dropped",
    created_at: new Date().toISOString(),
    price_history: makeHistory(29900, 24990, 30, 24990),
    neighbor_match: null,
    co2_saved_kg: 1.2,
    logistics_saved_inr: 320,
    email: "demo@example.com",
    email_sent: true,
    price_status: {
      status: "best",
      color_key: "green",
      label: "Best price",
      explanation: "Current price is at the low end of the seeded 30-day range.",
      confidence: 94,
      thirty_day_low_inr: 24990,
      thirty_day_high_inr: 29900,
      current_price_inr: 24990,
      deal_status: "best",
      deal_color: "green",
      deal_label: "Best price",
    },
  },
  {
    watch_id: "mock-2",
    sku: "LG-WM-7KG-2024",
    name: "LG 7kg Front-Load Washing Machine",
    brand: "LG",
    current_price_inr: 38450,
    target_price_inr: 34000,
    competitor_price_inr: 39990,
    competitor_source: "Croma",
    status: "watching",
    created_at: new Date().toISOString(),
    price_history: makeHistory(40990, 38450),
    neighbor_match: null,
    co2_saved_kg: 0,
    logistics_saved_inr: 0,
    email: "demo@example.com",
    email_sent: false,
    price_status: {
      status: "fair",
      color_key: "yellow",
      label: "Fair price",
      explanation: "Current price is within the normal 30-day band.",
      confidence: 82,
      thirty_day_low_inr: 38450,
      thirty_day_high_inr: 40990,
      current_price_inr: 38450,
      deal_status: "fair",
      deal_color: "yellow",
      deal_label: "Fair price",
    },
  },
  {
    watch_id: "mock-3",
    sku: "PHILIPS-AIRFRY-XL",
    name: "Philips Airfryer XL Essential",
    brand: "Philips",
    current_price_inr: 9499,
    target_price_inr: 9000,
    competitor_price_inr: 10999,
    competitor_source: "Amazon",
    status: "neighbor_match",
    created_at: new Date().toISOString(),
    price_history: makeHistory(11999, 9499, 30, 9499),
    neighbor_match: {
      product_id: "nbr-1",
      distance_km: 2.4,
      original_price_inr: 11999,
      logistics_cost_saved_inr: 450,
      neighbor_price_inr: 7800,
      co2_saved_kg: 0.86,
      day_appeared: 27,
    },
    co2_saved_kg: 0.86,
    logistics_saved_inr: 450,
    email: "demo@example.com",
    email_sent: true,
    price_status: {
      status: "best",
      color_key: "green",
      label: "Best price",
      explanation: "Price Guardian found a strong low-price signal and nearby match.",
      confidence: 96,
      thirty_day_low_inr: 9499,
      thirty_day_high_inr: 11999,
      current_price_inr: 9499,
      deal_status: "best",
      deal_color: "green",
      deal_label: "Best price",
    },
  },
  {
    watch_id: "mock-4",
    sku: "ACER-MON-27",
    name: 'Acer 27" QHD IPS Monitor',
    brand: "Acer",
    current_price_inr: 18990,
    target_price_inr: 18000,
    competitor_price_inr: 19999,
    competitor_source: "Reliance Digital",
    status: "watching",
    created_at: new Date().toISOString(),
    price_history: makeHistory(20990, 18990),
    neighbor_match: null,
    co2_saved_kg: 0,
    logistics_saved_inr: 0,
    email: null,
    email_sent: false,
    price_status: {
      status: "fair",
      color_key: "yellow",
      label: "Fair price",
      explanation: "Current price is watchable but not yet a strong low.",
      confidence: 78,
      thirty_day_low_inr: 18990,
      thirty_day_high_inr: 20990,
      current_price_inr: 18990,
      deal_status: "fair",
      deal_color: "yellow",
      deal_label: "Fair price",
    },
  },
  {
    watch_id: "mock-5",
    sku: "DYSON-V11",
    name: "Dyson V11 Cordless Vacuum",
    brand: "Dyson",
    current_price_inr: 41999,
    target_price_inr: 40000,
    competitor_price_inr: 43999,
    competitor_source: "Vijay Sales",
    status: "already_cheaper",
    created_at: new Date().toISOString(),
    price_history: makeHistory(44999, 41999),
    neighbor_match: null,
    co2_saved_kg: 0,
    logistics_saved_inr: 0,
    email: "demo@example.com",
    email_sent: true,
    price_status: {
      status: "fair",
      color_key: "yellow",
      label: "Fair price",
      explanation: "Current price beats competitor but is not the 30-day low.",
      confidence: 84,
      thirty_day_low_inr: 41999,
      thirty_day_high_inr: 44999,
      current_price_inr: 41999,
      deal_status: "fair",
      deal_color: "yellow",
      deal_label: "Fair price",
    },
  },
  {
    watch_id: "mock-6",
    sku: "BOAT-AIRDOPES",
    name: "boAt Airdopes 161 Pro",
    brand: "boAt",
    current_price_inr: 1299,
    target_price_inr: 1199,
    competitor_price_inr: 1499,
    competitor_source: "Flipkart",
    status: "watching",
    created_at: new Date().toISOString(),
    price_history: makeHistory(1599, 1299),
    neighbor_match: null,
    co2_saved_kg: 0,
    logistics_saved_inr: 0,
    email: null,
    email_sent: false,
    price_status: {
      status: "best",
      color_key: "green",
      label: "Best price",
      explanation: "Current price is near the bottom of the seeded range.",
      confidence: 91,
      thirty_day_low_inr: 1299,
      thirty_day_high_inr: 1599,
      current_price_inr: 1299,
      deal_status: "best",
      deal_color: "green",
      deal_label: "Best price",
    },
  },
  {
    watch_id: "mock-7",
    sku: "SAMSUNG-BUDS2-PRO",
    name: "Samsung Galaxy Buds2 Pro",
    brand: "Samsung",
    current_price_inr: 11999,
    target_price_inr: 10500,
    competitor_price_inr: 12990,
    competitor_source: "Amazon",
    status: "price_dropped",
    created_at: new Date().toISOString(),
    price_history: makeHistory(14999, 11999, 30, 11999),
    neighbor_match: null,
    co2_saved_kg: 0.4,
    logistics_saved_inr: 180,
    email: "demo@example.com",
    email_sent: true,
    price_status: {
      status: "best", color_key: "green", label: "Best price",
      explanation: "Dropped ₹3,000 in the last two weeks.",
      confidence: 92, thirty_day_low_inr: 11999, thirty_day_high_inr: 14999,
      current_price_inr: 11999, deal_status: "best", deal_color: "green", deal_label: "Best price",
    },
  },
  {
    watch_id: "mock-8",
    sku: "APPLE-IPAD-AIR",
    name: 'Apple iPad Air 11" (M2)',
    brand: "Apple",
    current_price_inr: 59900,
    target_price_inr: 56000,
    competitor_price_inr: 61999,
    competitor_source: "Vijay Sales",
    status: "watching",
    created_at: new Date().toISOString(),
    price_history: makeHistory(62900, 59900),
    neighbor_match: null, co2_saved_kg: 0, logistics_saved_inr: 0,
    email: "demo@example.com", email_sent: false,
    price_status: {
      status: "fair", color_key: "yellow", label: "Fair price",
      explanation: "Holding steady near the 30-day median.",
      confidence: 80, thirty_day_low_inr: 59900, thirty_day_high_inr: 62900,
      current_price_inr: 59900, deal_status: "fair", deal_color: "yellow", deal_label: "Fair price",
    },
  },
  {
    watch_id: "mock-9",
    sku: "NESPRESSO-VERTUO",
    name: "Nespresso Vertuo Pop Coffee Machine",
    brand: "Nespresso",
    current_price_inr: 14999,
    target_price_inr: 12000,
    competitor_price_inr: 16499,
    competitor_source: "Tata Cliq",
    status: "neighbor_match",
    created_at: new Date().toISOString(),
    price_history: makeHistory(17999, 14999, 30, 12500),
    neighbor_match: {
      product_id: "nbr-2", distance_km: 1.1,
      original_price_inr: 17999, logistics_cost_saved_inr: 320,
      neighbor_price_inr: 11200, co2_saved_kg: 0.72, day_appeared: 24,
    },
    co2_saved_kg: 0.72, logistics_saved_inr: 320,
    email: "demo@example.com", email_sent: true,
    price_status: {
      status: "best", color_key: "green", label: "Best price",
      explanation: "Neighbor selling barely used unit at a ₹3,800 discount.",
      confidence: 95, thirty_day_low_inr: 14999, thirty_day_high_inr: 17999,
      current_price_inr: 14999, deal_status: "best", deal_color: "green", deal_label: "Best price",
    },
  },
  {
    watch_id: "mock-10",
    sku: "MI-AIRPURIFIER-4",
    name: "Mi Air Purifier 4 Pro",
    brand: "Xiaomi",
    current_price_inr: 16499,
    target_price_inr: 15000,
    competitor_price_inr: 17999,
    competitor_source: "Flipkart",
    status: "watching",
    created_at: new Date().toISOString(),
    price_history: makeHistory(17999, 16499),
    neighbor_match: null, co2_saved_kg: 0, logistics_saved_inr: 0,
    email: null, email_sent: false,
    price_status: {
      status: "fair", color_key: "yellow", label: "Fair price",
      explanation: "Sale expected around Diwali — wait if you can.",
      confidence: 76, thirty_day_low_inr: 16499, thirty_day_high_inr: 17999,
      current_price_inr: 16499, deal_status: "fair", deal_color: "yellow", deal_label: "Fair price",
    },
  },
  {
    watch_id: "mock-11",
    sku: "LEVIS-511-SLIM",
    name: "Levi's 511 Slim Fit Jeans",
    brand: "Levi's",
    current_price_inr: 1799,
    target_price_inr: 1500,
    competitor_price_inr: 2499,
    competitor_source: "Myntra",
    status: "already_cheaper",
    created_at: new Date().toISOString(),
    price_history: makeHistory(2499, 1799),
    neighbor_match: null, co2_saved_kg: 0, logistics_saved_inr: 0,
    email: "demo@example.com", email_sent: true,
    price_status: {
      status: "best", color_key: "green", label: "Best price",
      explanation: "28% under Myntra's listing today.",
      confidence: 88, thirty_day_low_inr: 1799, thirty_day_high_inr: 2499,
      current_price_inr: 1799, deal_status: "best", deal_color: "green", deal_label: "Best price",
    },
  },
  {
    watch_id: "mock-12",
    sku: "KINDLE-PW-2024",
    name: "Kindle Paperwhite 16GB (2024)",
    brand: "Amazon",
    current_price_inr: 13999,
    target_price_inr: 11999,
    competitor_price_inr: null,
    competitor_source: null,
    status: "watching",
    created_at: new Date().toISOString(),
    price_history: makeHistory(14999, 13999),
    neighbor_match: null, co2_saved_kg: 0, logistics_saved_inr: 0,
    email: null, email_sent: false,
    price_status: {
      status: "fair", color_key: "yellow", label: "Fair price",
      explanation: "Awaiting Prime Day drop.",
      confidence: 74, thirty_day_low_inr: 13999, thirty_day_high_inr: 14999,
      current_price_inr: 13999, deal_status: "fair", deal_color: "yellow", deal_label: "Fair price",
    },
  },
];

export const MOCK_STATS = {
  total_saved_inr: 24267,
  total_co2_saved_kg: 3.18,
  count: MOCK_WATCHES.length,
  alerts: MOCK_WATCHES.filter((w) => w.status !== "watching").length,
};
