import type { WatchedItem } from "@/lib/watchlist-api";

function makeHistory(start: number, end: number, days = 30, dip?: number): { day: number; price: number }[] {
  const out: { day: number; price: number }[] = [];
  for (let i = 0; i < days; i++) {
    const t = i / (days - 1);
    const base = start + (end - start) * t;
    const noise = Math.sin(i * 1.3) * (start * 0.015) + Math.cos(i * 0.7) * (start * 0.01);
    let price = Math.round(base + noise);
    if (dip && i === days - 4) price = Math.round(dip);
    out.push({ day: i + 1, price });
  }
  return out;
}

export const MOCK_WATCHES: WatchedItem[] = [
  {
    watch_id: "mock-1",
    sku: "SONY-WH1000XM5",
    name: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    current_price_inr: 24990,
    target_price_inr: 23000,
    competitor_price_inr: 26499,
    competitor_source: "Flipkart",
    status: "price_dropped",
    created_at: new Date().toISOString(),
    price_history: makeHistory(29900, 24990, 30, 24990),
    neighbor_match: null,
    co2_saved_kg: 1.2,
    logistics_saved_inr: 320,
    email: "demo@example.com",
    email_sent: true,
    price_status: {
      status: "best",
      color_key: "green",
      label: "Best price",
      explanation: "Current price is at the low end of the seeded 30-day range.",
      confidence: 94,
      thirty_day_low_inr: 24990,
      thirty_day_high_inr: 29900,
      current_price_inr: 24990,
      deal_status: "best",
      deal_color: "green",
      deal_label: "Best price",
    },
  },
  {
    watch_id: "mock-2",
    sku: "LG-WM-7KG-2024",
    name: "LG 7kg Front-Load Washing Machine",
    brand: "LG",
    current_price_inr: 38450,
    target_price_inr: 34000,
    competitor_price_inr: 39990,
    competitor_source: "Croma",
    status: "watching",
    created_at: new Date().toISOString(),
    price_history: makeHistory(40990, 38450),
    neighbor_match: null,
    co2_saved_kg: 0,
    logistics_saved_inr: 0,
    email: "demo@example.com",
    email_sent: false,
    price_status: {
      status: "fair",
      color_key: "yellow",
      label: "Fair price",
      explanation: "Current price is within the normal 30-day band.",
      confidence: 82,
      thirty_day_low_inr: 38450,
      thirty_day_high_inr: 40990,
      current_price_inr: 38450,
      deal_status: "fair",
      deal_color: "yellow",
      deal_label: "Fair price",
    },
  },
  {
    watch_id: "mock-3",
    sku: "PHILIPS-AIRFRY-XL",
    name: "Philips Airfryer XL Essential",
    brand: "Philips",
    current_price_inr: 9499,
    target_price_inr: 9000,
    competitor_price_inr: 10999,
    competitor_source: "Amazon",
    status: "neighbor_match",
    created_at: new Date().toISOString(),
    price_history: makeHistory(11999, 9499, 30, 9499),
    neighbor_match: {
      product_id: "nbr-1",
      distance_km: 2.4,
      original_price_inr: 11999,
      logistics_cost_saved_inr: 450,
      neighbor_price_inr: 7800,
      co2_saved_kg: 0.86,
      day_appeared: 27,
    },
    co2_saved_kg: 0.86,
    logistics_saved_inr: 450,
    email: "demo@example.com",
    email_sent: true,
    price_status: {
      status: "best",
      color_key: "green",
      label: "Best price",
      explanation: "Price Guardian found a strong low-price signal and nearby match.",
      confidence: 96,
      thirty_day_low_inr: 9499,
      thirty_day_high_inr: 11999,
      current_price_inr: 9499,
      deal_status: "best",
      deal_color: "green",
      deal_label: "Best price",
    },
  },
  {
    watch_id: "mock-4",
    sku: "ACER-MON-27",
    name: 'Acer 27" QHD IPS Monitor',
    brand: "Acer",
    current_price_inr: 18990,
    target_price_inr: 18000,
    competitor_price_inr: 19999,
    competitor_source: "Reliance Digital",
    status: "watching",
    created_at: new Date().toISOString(),
    price_history: makeHistory(20990, 18990),
    neighbor_match: null,
    co2_saved_kg: 0,
    logistics_saved_inr: 0,
    email: null,
    email_sent: false,
    price_status: {
      status: "fair",
      color_key: "yellow",
      label: "Fair price",
      explanation: "Current price is watchable but not yet a strong low.",
      confidence: 78,
      thirty_day_low_inr: 18990,
      thirty_day_high_inr: 20990,
      current_price_inr: 18990,
      deal_status: "fair",
      deal_color: "yellow",
      deal_label: "Fair price",
    },
  },
  {
    watch_id: "mock-5",
    sku: "DYSON-V11",
    name: "Dyson V11 Cordless Vacuum",
    brand: "Dyson",
    current_price_inr: 41999,
    target_price_inr: 40000,
    competitor_price_inr: 43999,
    competitor_source: "Vijay Sales",
    status: "already_cheaper",
    created_at: new Date().toISOString(),
    price_history: makeHistory(44999, 41999),
    neighbor_match: null,
    co2_saved_kg: 0,
    logistics_saved_inr: 0,
    email: "demo@example.com",
    email_sent: true,
    price_status: {
      status: "fair",
      color_key: "yellow",
      label: "Fair price",
      explanation: "Current price beats competitor but is not the 30-day low.",
      confidence: 84,
      thirty_day_low_inr: 41999,
      thirty_day_high_inr: 44999,
      current_price_inr: 41999,
      deal_status: "fair",
      deal_color: "yellow",
      deal_label: "Fair price",
    },
  },
  {
    watch_id: "mock-6",
    sku: "BOAT-AIRDOPES",
    name: "boAt Airdopes 161 Pro",
    brand: "boAt",
    current_price_inr: 1299,
    target_price_inr: 1199,
    competitor_price_inr: 1499,
    competitor_source: "Flipkart",
    status: "watching",
    created_at: new Date().toISOString(),
    price_history: makeHistory(1599, 1299),
    neighbor_match: null,
    co2_saved_kg: 0,
    logistics_saved_inr: 0,
    email: null,
    email_sent: false,
    price_status: {
      status: "best",
      color_key: "green",
      label: "Best price",
      explanation: "Current price is near the bottom of the seeded range.",
      confidence: 91,
      thirty_day_low_inr: 1299,
      thirty_day_high_inr: 1599,
      current_price_inr: 1299,
      deal_status: "best",
      deal_color: "green",
      deal_label: "Best price",
    },
  },
];

export const MOCK_STATS = {
  total_saved_inr: 9725,
  total_co2_saved_kg: 2.06,
  count: MOCK_WATCHES.length,
  alerts: MOCK_WATCHES.filter((w) => w.status !== "watching").length,
};
